from __future__ import annotations

import hashlib
import os
from dataclasses import dataclass, field
from typing import List, Tuple, Dict, Optional, Set

from antlr4 import FileStream, InputStream, CommonTokenStream
from antlr4.error.ErrorListener import ErrorListener
from antlr4.error.ErrorStrategy import DefaultErrorStrategy

# Generated by ANTLR (after you run the generator)
from gen.MiniPyLexer import MiniPyLexer
from gen.MiniPyParser import MiniPyParser
from gen.MiniPyVisitor import MiniPyVisitor


# ---------------- Error handling ----------------

class CollectingErrorListener(ErrorListener):
    """Collects lexer/parser errors instead of printing them."""
    def __init__(self) -> None:
        super().__init__()
        self.errors: List[str] = []

    def syntaxError(self, recognizer, offendingSymbol, line, column, msg, e):
        self.errors.append(f"Line {line}:{column} {msg}")


class StrictErrorStrategy(DefaultErrorStrategy):
    """
    A stricter strategy: still attempts recovery but tracks that we recovered.
    In a report, it's good to show error recovery vs fatal failures.
    """
    def __init__(self) -> None:
        super().__init__()
        self.recovered: bool = False

    def recover(self, recognizer, e):
        self.recovered = True
        super().recover(recognizer, e)

    def recoverInline(self, recognizer):
        self.recovered = True
        return super().recoverInline(recognizer)


# ---------------- AST representation ----------------

@dataclass
class ASTNode:
    kind: str
    value: Optional[str] = None
    children: List["ASTNode"] = field(default_factory=list)
    # optional source info (useful for highlighting)
    line: Optional[int] = None
    col: Optional[int] = None

    def pretty(self, indent: int = 0) -> str:
        pad = "  " * indent
        v = f":{self.value}" if self.value is not None else ""
        loc = f" @{self.line}:{self.col}" if self.line is not None else ""
        s = f"{pad}{self.kind}{v}{loc}\n"
        for ch in self.children:
            s += ch.pretty(indent + 1)
        return s


# ---------------- Parse tree -> AST visitor ----------------

class ASTBuilder(MiniPyVisitor):
    """
    Converts the ANTLR parse tree into a simplified AST.
    Also performs normalization to resist renaming attacks:
      - identifiers -> ID
      - numbers -> NUM
    """
    def visitProgram(self, ctx):
        stmts = [self.visit(s) for s in ctx.statement()]
        return ASTNode("Program", children=stmts)

    def visitAssignStmt(self, ctx):
        name_tok = ctx.NAME().getSymbol()
        # normalize variable name
        left = ASTNode("Id", value="ID", line=name_tok.line, col=name_tok.column)
        right = self.visit(ctx.expr())
        return ASTNode("Assign", children=[left, right], line=name_tok.line, col=name_tok.column)

    def visitIfStmt(self, ctx):
        # 'if' token is literal; location isn't exposed directly, so attach from first child
        cond = self.visit(ctx.expr())
        body = [self.visit(s) for s in ctx.statement()]
        return ASTNode("If", children=[cond, ASTNode("Block", children=body)])

    def visitWhileStmt(self, ctx):
        cond = self.visit(ctx.expr())
        body = [self.visit(s) for s in ctx.statement()]
        return ASTNode("While", children=[cond, ASTNode("Block", children=body)])

    def visitAddSubExpr(self, ctx):
        op = ctx.op.text
        left = self.visit(ctx.expr(0))
        right = self.visit(ctx.expr(1))
        return ASTNode("BinOp", value=op, children=[left, right])

    def visitMulDivExpr(self, ctx):
        op = ctx.op.text
        left = self.visit(ctx.expr(0))
        right = self.visit(ctx.expr(1))
        return ASTNode("BinOp", value=op, children=[left, right])

    def visitAtomExpr(self, ctx):
        return self.visit(ctx.atom())

    def visitAtom(self, ctx):
        if ctx.NAME():
            tok = ctx.NAME().getSymbol()
            return ASTNode("Id", value="ID", line=tok.line, col=tok.column)
        if ctx.NUMBER():
            tok = ctx.NUMBER().getSymbol()
            return ASTNode("Num", value="NUM", line=tok.line, col=tok.column)
        # ( expr )
        return self.visit(ctx.expr())


# ---------------- Indentation preprocessing ----------------

def inject_indent_markers(code: str) -> str:
    """
    Very simple indentation handler:
    - converts leading spaces changes into <INDENT>/<DEDENT> lines.
    - This is a teaching/demo approach, not full Python spec.

    Assumption:
      - indentation is multiples of 4 spaces.
      - blocks appear after ':' newline.
    """
    lines = code.splitlines()
    out: List[str] = []
    indent_stack = [0]

    for raw in lines:
        # keep empty lines
        if raw.strip() == "":
            out.append("")  # preserve line breaks
            continue

        leading = len(raw) - len(raw.lstrip(" "))
        current = indent_stack[-1]

        if leading > current:
            indent_stack.append(leading)
            out.append("<INDENT>")
        while leading < indent_stack[-1]:
            indent_stack.pop()
            out.append("<DEDENT>")

        out.append(raw.lstrip(" "))

    # close remaining indents
    while len(indent_stack) > 1:
        indent_stack.pop()
        out.append("<DEDENT>")

    # re-add newlines
    return "\n".join(out) + "\n"


# ---------------- Parsing pipeline ----------------

@dataclass
class ParseResult:
    ast: Optional[ASTNode]
    errors: List[str]
    recovered: bool


def parse_minipy(source_code: str) -> ParseResult:
    """
    Parses MiniPy source code and returns AST, errors, and whether parser recovered.
    """
    pre = inject_indent_markers(source_code)
    inp = InputStream(pre)

    lexer = MiniPyLexer(inp)
    lex_err = CollectingErrorListener()
    lexer.removeErrorListeners()
    lexer.addErrorListener(lex_err)

    tokens = CommonTokenStream(lexer)

    parser = MiniPyParser(tokens)
    par_err = CollectingErrorListener()
    parser.removeErrorListeners()
    parser.addErrorListener(par_err)

    strategy = StrictErrorStrategy()
    parser._errHandler = strategy

    tree = parser.program()

    errors = lex_err.errors + par_err.errors
    if errors:
        # If there are errors, we still may have partial AST via recovery.
        # Decide based on your course rubric whether to accept or reject.
        pass

    builder = ASTBuilder()
    ast = builder.visit(tree) if tree is not None else None
    return ParseResult(ast=ast, errors=errors, recovered=strategy.recovered)


# ---------------- Similarity via subtree fingerprints ----------------

def canonical_form(node: ASTNode) -> str:
    """
    Canonical string of subtree shape (structure + operator kinds).
    Identifiers and numbers are already normalized.
    """
    v = "" if node.value is None else f"={node.value}"
    child_forms = ",".join(canonical_form(ch) for ch in node.children)
    return f"{node.kind}{v}({child_forms})"


def subtree_hashes(node: ASTNode, out: Optional[Dict[str, List[ASTNode]]] = None) -> Dict[str, List[ASTNode]]:
    """
    Computes a Merkle-style hash for each subtree, returns mapping:
      hash -> list of AST nodes producing that hash
    """
    if out is None:
        out = {}

    # compute children first
    child_hashes = []
    for ch in node.children:
        subtree_hashes(ch, out)
        # get canonical and hash for child (deterministic)
        ch_c = canonical_form(ch)
        child_hashes.append(hashlib.sha256(ch_c.encode("utf-8")).hexdigest())

    here = f"{node.kind}|{node.value}|{'/'.join(child_hashes)}"
    h = hashlib.sha256(here.encode("utf-8")).hexdigest()

    out.setdefault(h, []).append(node)
    return out


def jaccard_similarity(set_a: Set[str], set_b: Set[str]) -> float:
    if not set_a and not set_b:
        return 1.0
    inter = len(set_a & set_b)
    union = len(set_a | set_b)
    return inter / union if union else 0.0


@dataclass
class SimilarityReport:
    similarity: float
    common_hashes: List[str]
    count_common: int
    total_a: int
    total_b: int


def compare_ast(ast_a: ASTNode, ast_b: ASTNode) -> SimilarityReport:
    map_a = subtree_hashes(ast_a)
    map_b = subtree_hashes(ast_b)

    hashes_a = set(map_a.keys())
    hashes_b = set(map_b.keys())

    common = sorted(list(hashes_a & hashes_b))
    sim = jaccard_similarity(hashes_a, hashes_b)

    return SimilarityReport(
        similarity=sim,
        common_hashes=common,
        count_common=len(common),
        total_a=len(hashes_a),
        total_b=len(hashes_b),
    )


# ---------------- CLI / demo ----------------

def read_text(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def main(file1: str, file2: str) -> None:
    code1 = read_text(file1)
    code2 = read_text(file2)

    r1 = parse_minipy(code1)
    r2 = parse_minipy(code2)

    # Error handling outcomes for report screenshots/logs
    if r1.errors:
        print(f"[{file1}] Errors:")
        for e in r1.errors:
            print("  ", e)
        print("Recovered:", r1.recovered)
    if r2.errors:
        print(f"[{file2}] Errors:")
        for e in r2.errors:
            print("  ", e)
        print("Recovered:", r2.recovered)

    if r1.ast is None or r2.ast is None:
        raise RuntimeError("Parsing failed: AST not produced.")

    report = compare_ast(r1.ast, r2.ast)

    print("\n--- Similarity Report ---")
    print(f"Subtree Jaccard Similarity: {report.similarity * 100:.2f}%")
    print(f"Total subtrees A: {report.total_a}")
    print(f"Total subtrees B: {report.total_b}")
    print(f"Common subtree patterns: {report.count_common}")

    # For a report: show a few matched hashes as evidence
    print("\nSample matched subtree hashes (first 5):")
    for h in report.common_hashes[:5]:
        print("  ", h)


if __name__ == "__main__":
    import sys
    if len(sys.argv) != 3:
        print("Usage: python plag_detector.py <file1.mpy> <file2.mpy>")
        raise SystemExit(2)
    main(sys.argv[1], sys.argv[2])
